### ISSUE TITLE
state_attribute does not work

### ISSUE THREAD

**Issue by olivermt** [ash-project/ash_state_machine#12]
I have this:

```
state_machine do
    initial_states [:initialized]
    default_initial_state :initialized
    state_attribute :status

    transitions do
      # transition :upload, from: :initialized, to: :uploading
      # transition :process, from: :uploading, to: :processing
      # transition :fail, from: :processing, to: :failed
      # transition :complete, from: :processing, to: :completed
    end
  end
```
And when loading the resource that has the state machine from the parent resource I get:

```
iex(2)> vom = Safari.Virtual.VirtualOutcropModel.by_id!(303, load: :cesium_asset)
[debug] QUERY OK source="virtual_outcrop_models" db=0.8ms queue=0.9ms idle=1120.9ms
SELECT v0."id" FROM "virtual_outcrop_models" AS v0 WHERE (v0."id"::bigint = $1::bigint) [303]
↳ AshPostgres.DataLayer.run_query/2, at: lib/data_layer.ex:629
[debug] QUERY ERROR source="cesium_assets" db=0.0ms queue=3.5ms idle=1131.6ms
SELECT c0."status", c0."id", c0."state", c0."cesium_id", c0."tileset_url", c0."cesium_progress", c0."default_camera", c0."cesium_bucket_credentials", c0."virtual_outcrop_model_id" FROM "cesium_assets" AS c0 WHERE (c0."virtual_outcrop_model_id"::bigint = $1::bigint) [303]
↳ AshPostgres.DataLayer.run_query/2, at: lib/data_layer.ex:629
** (Ash.Error.Unknown) Unknown Error

* ** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.state does not exist

    query: SELECT c0."status", c0."id", c0."state", c0."cesium_id", c0."tileset_url", c0."cesium_progress", c0."default_camera", c0."cesium_bucket_credentials", c0."virtual_outcrop_model_id" FROM "cesium_assets" AS c0 WHERE (c0."virtual_outcrop_model_id"::bigint = $1::bigint)

    hint: Perhaps you meant to reference the column "c0.status".
    (ash 2.15.6) lib/ash/api/api.ex:2183: Ash.Api.unwrap_or_raise!/3
    (safari 0.1.0) deps/ash/lib/ash/code_interface.ex:515: Safari.Virtual.VirtualOutcropModel.by_id!/3
    iex:2: (file)
```

**Comment by zachdaniel** [comment]
The fact that it is selecting
`c0."status", c0."id", c0."state"`

makes me wonder if perhaps you still have a `state` attribute in your resource that isn't present in the table?

**Comment by olivermt** [comment]
I had a attribute before that was named `status` which I removed when adding the state machine, but never had any attribute named `state`.

**Comment by zachdaniel** [comment]
What does `Ash.Resource.Info.attributes(Resource)` show?

**Comment by olivermt** [comment]
I renamed everything to `state` to get on with it and I am like 25 commits deep since that, so I am not sure I can reproduce this again 😬 
In hindsight I should have branched it out, sorry.

I suspect this is some kind of compile race error and that I inadvertantly fixed it when I just homogenized on one attribute.

**Comment by zachdaniel** [comment]
No worries 😂 I'll add a test confirming the behavior at a minimum as it appears one does not exist.

**Comment by zachdaniel** [comment]
Still haven't had time to look at this. I'll mark it as a good first issue and will track it down when we have a reproduction/if someone else encounters it.

**Comment by zachdaniel** [comment]
I was never able to reproduce it, and no one else has reported it, so closing for now.
